/*
 * Generates data/words.js from tools/words5.txt and precomputes the solver's first guess
 * and whole-tree statistics (these take a few seconds, so the page loads them ready-made).
 *
 *   node tools/build-data.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const ctx = { self: {}, console };
vm.createContext(ctx);
for (const f of ['graph.js', 'dijkstra.js', 'bridges.js', 'solver.js']) {
  vm.runInContext(fs.readFileSync(path.join(root, 'core', f), 'utf8'), ctx, { filename: f });
}
const WG = ctx.self.WG;

const words = fs.readFileSync(path.join(__dirname, 'words5.txt'), 'utf8')
  .split(/\s+/).map((w) => w.trim().toLowerCase()).filter((w) => /^[a-z]{5}$/.test(w));
const list = [...new Set(words)].sort();
console.log('words:', list.length);

let t = Date.now();
const first = WG.bestGuess(list, list);
console.log('first guess:', first, (Date.now() - t) + 'ms');

t = Date.now();
const tree = WG.solveAll(list, first.guess);
console.log('tree:', tree, (Date.now() - t) + 'ms');

// Default ladder: a friendly pair of common words, 4-7 steps apart.
const G = WG.buildGraph(list);
const pairs = [['sleep', 'dream'], ['black', 'white'], ['stone', 'bread'], ['sleep', 'dream'], ['smile', 'frown'], ['cloud', 'storm'], ['train', 'plane'], ['sweet', 'spicy'], ['mouse', 'tiger'], ['plant', 'grass'], ['heart', 'brain']];
let ladder = null;
for (const [a, b] of pairs) {
  if (!G.index.has(a) || !G.index.has(b)) continue;
  const r = WG.bfs(G, G.index.get(a), G.index.get(b));
  console.log(a, b, r.path ? r.path.length - 1 : 'unreachable');
  if (!ladder && r.path && r.path.length - 1 >= 4 && r.path.length - 1 <= 8) ladder = [a, b];
}
console.log('default ladder:', ladder);

const meta = { first: first.guess, firstWorst: first.worst, firstGroups: first.groups, tree, ladder };
const out = `/* Generated by tools/build-data.js from tools/words5.txt. Do not edit by hand. */
self.WG = self.WG || {};
self.WG.WORDS = ${JSON.stringify(list)};
self.WG.META = ${JSON.stringify(meta)};
`;
fs.writeFileSync(path.join(root, 'data', 'words.js'), out);
console.log('wrote data/words.js');
